### ISSUE TITLE
Missing type info

### ISSUE THREAD

**Issue by haraldrombaut** [bguerout/jongo#258]
https://github.com/bguerout/jongo/commit/6e7396623ad298d44c3662c2ab23b3e4092fb8d8 (and the current version on master) introduced a bug for me. Sometimes the first byte of the document is 0 which causes the parameter to be marshalled again in a wrapped object.

As a result of this, the json type info is not added anymore (annotated with @JsonTypeInfo(use = CUSTOM, property = "type")) and my object can no longer be unmarshalled because of the missing type info.

**Comment by bguerout** [comment]
Hello,

Sorry for this bug.
Do you have a test case ?
I have recently updated this code with https://github.com/bguerout/jongo/commit/e2bfd71407549d9efb361e21874d4795587eaa03 but this seems not enough

**Comment by haraldrombaut** [comment]
the problem occurs when the document byte % 256 == 0

```java
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.github.fakemongo.Fongo;
import com.lordofthejars.nosqlunit.annotation.UsingDataSet;
import com.lordofthejars.nosqlunit.mongodb.MongoDbRule;
import com.mongodb.Mongo;
import org.bson.types.ObjectId;
import org.jongo.Jongo;
import org.jongo.MongoCollection;
import org.jongo.marshall.jackson.oid.MongoId;
import org.jongo.marshall.jackson.oid.MongoObjectId;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import static com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME;
import static com.lordofthejars.nosqlunit.core.LoadStrategyEnum.DELETE_ALL;
import static com.lordofthejars.nosqlunit.mongodb.MongoDbRule.MongoDbRuleBuilder.newMongoDbRule;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes = JongoTest.JongoConfiguration.class)
@UsingDataSet(loadStrategy = DELETE_ALL)
public class JongoTest {

    public static final String CUSTOM = "CUSTOM";
    @Rule
    public MongoDbRule mongoDbRule = newMongoDbRule().defaultSpringMongoDb("test");

    @Autowired
    private ApplicationContext applicationContext;
    @Autowired
    private Jongo jongo;

    @Test
    public void testUpdate() throws Exception {
        MongoCollection collection = jongo.getCollection("test");
        Custom custom = new Custom();
        collection.insert(custom);
        collection.update(new ObjectId(custom.id)).with("#", custom);
    }

    @Configuration
    static class JongoConfiguration {

        @Bean
        public Mongo mongo() {
            return new Fongo("InMemoryMongo").getMongo();
        }

        @Bean
        public Jongo jongo(Mongo mongo) {
            return new Jongo(mongo.getDB("test"));
        }
    }

    @JsonTypeInfo(use = NAME, property = "type")
    @JsonSubTypes(@Type(value = Custom.class, name = CUSTOM))
    static class Base {

        @MongoObjectId
        @MongoId
        protected String id;
        private String test = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";

        protected Base() {
        }
    }

    @JsonTypeName(CUSTOM)
    static class Custom extends Base {
    }
}
```

**Comment by bguerout** [comment]
Hello, sorry for the late response.
I'm unable to reproduce the bug with Jongo and real Mongo database.

Have you ran your test without Fongo.

**Comment by haraldrombaut** [comment]
Yes I have. This test does indeed not fail, but if you add 
```java
collection.findOne().as(Custom.class);
```
under the update statement, it will throw an exception.

If you look in the collection (if run with a real mongo) the document that is saved, does not have a field type.

**Comment by bguerout** [comment]
OK now it fails !

**Comment by bguerout** [comment]
I've fixed the test. IHMO this is not due to the commit you have mentioned.

```java
    @Test
    public void testUpdate() throws Exception {
        Custom custom = new Custom();
        collection.insert(custom);
        collection.update(new ObjectId(custom.id)).with(custom);//without # query

        collection.findOne().as(Custom.class);
    }
```

```.with("#", custom)``` updates document with a new one -> ```"{test:'aaaaaaa'}"``` 
```.with(custom)``` updates document with a set operator ```"{$set:{test:'aaaaa'}}"```

**Comment by bguerout** [comment]
My previous comment is just wrong.

**Comment by haraldrombaut** [comment]
Thought so, I need the # query, because of reasons explained in #231 and #226

**Comment by bguerout** [comment]
I haven't spent enough time to understand what's happen between Jackson and Bson4jackson when this POJO is se/derialized.
Can you test this fix ? I can create an early release if you need it.

**Comment by haraldrombaut** [comment]
This still doesn't work. The first byte is 0, so the commit has not really changed anything.

**Comment by bguerout** [comment]
Should be fine now.

**Comment by bguerout** [comment]
The hasBeenSerializedAsPrimitive try to detect when a POJO parameter has been serialized into a primitive. To check this we have to evaluate document size, nevertheless this check was buggy.

**Comment by haraldrombaut** [comment]
:+1: seems to work now

**Comment by bguerout** [comment]
Here is an early version
**This version must be considered as a SNAPSHOT of future 1.3 release**
```xml
<dependencies>
  <dependency>
    <groupId>org.jongo</groupId>
    <artifactId>jongo</artifactId>
    <version>1.3-early-20150728-0456</version>
  </dependency>
</dependencies>
...
<repositories>
    <repository>
       <id>cloudbees-jongo-early-release</id>
        <url>http://repository-jongo.forge.cloudbees.com/release</url>
        <releases>
            <enabled>true</enabled>
        </releases>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </repository>
</repositories>
```

**Comment by bguerout** [comment]
1.3.0 has been released.
